""" process lines that look like
1 <stop tag="64" title="Dudley Station - Harvard Side" lat="42.3294799" lon="-71.08391" stopId="00064"/>

and make a proper python importable table of tags, lats, and lons
""" 

import sys
import re

def interpret_stop_string(s):
  tag = re.match('.* tag="([^"]*)".*',s).groups(0)[0]
  lat =  re.match('.* lat="([^"]*)".*',s).groups(0)[0]
  lon = re.match('.* lon="([^"]*)".*',s).groups(0)[0]
  return tag, lat, lon

def start(fname):
  print "# this file is autogenerated by update_stop_table.sh"
  print "table = ["
  for line in open(fname):
    route, stop_string = line.strip().split(" ", 1)

    try:
        tag, lat, lon = interpret_stop_string(stop_string)
    except AttributeError:
        pass
    
    print "('%s', '%s', %s, %s)," % (route, tag, lat, lon)
  print "]"

if __name__ == "__main__":
  start(*sys.argv[1:])
